name: realtime-polio
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - nodejs=12.11.1
  - mafft
  - medaka=0.10.0
  - minimap2=2.17
  - pandas=0.25.2
  - pip=19.3.1
  - python=3.6
  - samtools=1.9
  - snakemake-minimal
  - racon=1.4.7
  - artic-network::rampart=1.0.2
  - pip:
    - msgpack==0.6.2
    - binlorry==1.3.0a1
    - git+https://github.com/artic-network/Porechop.git@v0.3.1pre
    - git+https://github.com/rmcolq/postbox.git@v0.4
    - h5py==2.7.1 
    - pytools
    - scipy==1.3.1
    - seaborn
    - tensorflow==1.14.0
    - matplotlib==3.1.1
