##### Where is the data? #####

input_path: path/to/data
annotated_path: path/to/csv
output_path: path/to/binned #where rampart will put the binned/ filtered files 

##### Mapping reference panel #####

references_file: ../../references.fasta

##### Barcodes to process #####


##### Read length filtering range #####

min_read_length: 800
max_read_length: 1400

##### Read thresholds #####

min_reads: 50
min_pcent: 0.01

##### Analysis Stem #####
