##### Where is the data? #####

input_path: path/to/data
annotated_path: annotations
output_path: analysis 

##### Mapping reference panel #####

references_file: ../../references.fasta

##### Barcodes to process #####


##### Read length filtering range #####

min_read_length: 1000
max_read_length: 1300

##### Read thresholds #####

min_reads: 50
min_pcent: 0.01

##### Analysis Stem #####
